/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FifoJni_lib_FifoCalculator */

#ifndef _Included_FifoJni_lib_FifoCalculator
#define _Included_FifoJni_lib_FifoCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FifoJni_lib_FifoCalculator
 * Method:    fifo
 * Signature: ([CI)[C
 */
JNIEXPORT jcharArray JNICALL Java_FifoJni_lib_FifoCalculator_fifo
  (JNIEnv *, jobject, jcharArray, jint);

#ifdef __cplusplus
}
#endif
#endif
