/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Operativos_JavaFifo */

#ifndef _Included_Operativos_JavaFifo
#define _Included_Operativos_JavaFifo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Operativos_JavaFifo
 * Method:    fifo
 * Signature: ([Ljava/lang/String;I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_Operativos_JavaFifo_fifo
  (JNIEnv *, jobject, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
